" -------- Vim-Plug SECTION --------
" Specify a directory for plugins
" Run :PlugInstall to install
" :PlugUpdate to update plugins
" :PlugUpgrade to upgrade vim-plug itself
call plug#begin('~/.vim/plugged')
Plug 'http://github.com/scrooloose/nerdtree.git'                    " NERDtree explorer
Plug 'https://github.com/tomasr/molokai.git'                        " Molokai theme
Plug 'https://github.com/vim-airline/vim-airline.git'               " Vim-airline
Plug 'https://github.com/pangloss/vim-javascript.git'               " Vim-JavaScript
Plug 'https://github.com/othree/html5.vim.git'                      " HTML5 for Vim
Plug 'https://github.com/mxw/vim-jsx.git'                           " JSX for Vim
Plug 'https://github.com/jiangmiao/auto-pairs.git'                  " Auto-pairs {}[]()
call plug#end()

" -------- GENERAL SETTINGS --------
"  Make the backspace work like in most programs
set backspace=indent,eol,start

" Line numbers
set number

" Set autoread when a file is modified on the outside
set autoread

" Turn on the Wild menu
set wildmenu

" Ignore case when searching
set ignorecase

" Highlight search results
set hlsearch

" Makes search act like in modern browsers
set incsearch

" Don't redraw in macros - good for performance
set lazyredraw

" No sounds on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" -------- SYNTAX, FONTS AND COLORS --------
" Syntax highlighting
syntax enable

" Set encoding to UTF8
set encoding=utf8

" Use spaces instead of tabs
set expandtab

" Smart tabs
set smarttab

" 1 tab = 4 spaces
set shiftwidth=4
set tabstop=4

" Default theme
colorscheme molokai

" -------- STATUS LINE --------
" Always show the status line
set laststatus=2

" -------- MAPPINGS --------
" Open/close NERDTree
map <C-n> : NERDTreeToggle<CR>
